#! /bin/sh
### BEGIN INIT INFO
# Provides:          display_daemon
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: System Monitor on Oled Display Daemon
# Description:       Display Daemon service
### END INIT INFO

# Author: Gabriel Marti <gabimarti at gmail dot com> | Twitter <@310hkc41b>

SCRIPT=/home/pi/oledmonitor/stats.py
RUNAS=root
DESC="Display Daemon service"
NAME=$(basename $0)
PIDDIR=/var/run/$NAME/
LOGDIR=/var/log/$NAME/
PIDFILE=$PIDDIR$NAME.pid
LOGFILE=$LOGDIR$NAME.log


start() {
  if [ ! -d "$PIDDIR" ]; then
    echo "Error: ${PIDDIR} not found. Create it..."
    sudo mkdir $PIDDIR
  fi

  if [ ! -d "$LOGDIR" ]; then
    sudo echo "Error: ${LOGDIR} not found. Create it..."
    sudo mkdir $LOGDIR
  fi

  if [ -f $PIDFILE ] && (kill -0 $(cat $PIDFILE) 2> /dev/null); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service…' >&2
  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

status() {
  echo 'Service status…'
  return 0
}

uninstall() {
  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
    rm -f "$PIDFILE"
    echo "Notice: log file is not be removed: '$LOGFILE'" >&2
    update-rc.d -f $NAME remove
    rm -fv "$0"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart)
    stop
    start
    ;;
  uninstall)
    uninstall
    ;;
  *)
    echo "Usage: sudo $0 {start|stop|status|restart|uninstall}"
esac

